---
namespace: rust-rest-dev
bases:
  - ../base
resources:
  - ns.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: rust-rest
    path: deployment-patch.yaml
